export const movies = [
    {
        "id": "1",
        "title": "Game Night",
        "year": "2018",
        "genres": [
            "Action",
            "Comedy",
            "Crime"
        ],
        "ratings": [
            2,
            10,
            1,
            10,
            6,
            2,
            5,
            2,
            9,
            7,
            5,
            3,
            7,
            7,
            1,
            4,
            5,
            9,
            2,
            8,
            10,
            8,
            1,
            10,
            7,
            10,
            8,
            6,
            7,
            6
        ],
        "contentRating": "11",
        "releaseDate": "2018-02-28",
        "storyline": "A group of friends who meet regularly for game nights find themselves trying to solve a murder mystery.",
        "actors": [
            "Rachel McAdams",
            "Jesse Plemons",
            "Jason Bateman"
        ],
        "imdbRating": "",
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjQxMDE5NDg0NV5BMl5BanBnXkFtZTgwNTA5MDE2NDM@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
        "id": "2",
        "title": "Area X: Annihilation",
        "year": "2018",
        "genres": [
            "Adventure",
            "Drama",
            "Fantasy"
        ],
        "ratings": [
            2,
            6,
            2,
            3,
            9,
            5,
            3,
            10,
            6,
            7,
            3,
            1,
            6,
            6,
            1,
            7,
            8,
            8,
            7,
            2,
            3,
            2,
            10,
            4,
            9,
            8,
            2,
            2,
            6,
            3
        ],
        "contentRating": "R",
        "releaseDate": "2018-02-23",
        "storyline": "A biologist's husband disappears. She puts her name forward for an expedition into an environmental disaster zone, but does not find what she's expecting. The expedition team is made up of the biologist, an anthropologist, a psychologist, a surveyor, and a linguist.",
        "actors": [
            "Tessa Thompson",
            "Jennifer Jason Leigh",
            "Natalie Portman"
        ],
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTk2Mjc2NzYxNl5BMl5BanBnXkFtZTgwMTA2OTA1NDM@._V1_SY500_CR0,0,320,500_AL_.jpg"
    },
    {
        "id": "3",
        "title": "Hannah",
        "year": "2017",
        "genres": [
            "Drama"
        ],
        "ratings": [
            1,
            10,
            4,
            9,
            10,
            1,
            9,
            3,
            4,
            4,
            3,
            2,
            3,
            3,
            1,
            1,
            6,
            7,
            10,
            7,
            7,
            8,
            1,
            3,
            10,
            3,
            1,
            9,
            7,
            3
        ],
        "contentRating": "",
        "duration": "PT95M",
        "releaseDate": "2018-01-24",
        "storyline": "Intimate portrait of a woman drifting between reality and denial when she is left alone to grapple with the consequences of her husband's imprisonment.",
        "actors": [
            "Charlotte Rampling",
            "Andr Wilms",
            "Stphanie Van Vyve"
        ],
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNWJmMWIxMjQtZTk0Mi00YTE0LTkyNzAtYzQxYjcwYjE4ZDk2XkEyXkFqcGdeQXVyMTc4MzI2NQ@@._V1_SY500_SX350_AL_.jpg"
    },
    {
        "id": "4",
        "title": "The Lodgers",
        "year": "2017",
        "genres": [
            "Drama",
            "Horror",
            "Romance"
        ],
        "ratings": [
            7,
            5,
            1,
            5,
            4,
            10,
            2,
            7,
            6,
            4,
            10,
            5,
            1,
            5,
            3,
            6,
            9,
            1,
            3,
            4,
            9,
            1,
            7,
            6,
            7,
            5,
            7,
            2,
            10,
            10
        ],
        "contentRating": "R",
        "releaseDate": "2018-03-09",
        "storyline": "1920, rural Ireland. Anglo Irish twins Rachel and Edward share a strange existence in their crumbling family estate. Each night, the property becomes the domain of a sinister presence (The Lodgers) which enforces three rules upon the twins: they must be in bed by midnight; they may not permit an outsider past the threshold; if one attempts to escape, the life of the other is placed in jeopardy. When troubled war veteran Sean returns to the nearby village, he is immediately drawn to the mysterious Rachel, who in turn begins to break the rules set out by The Lodgers. The consequences pull Rachel into a deadly confrontation with her brother - and with the curse that haunts them.",
        "actors": [
            "Charlotte Vega",
            "David Bradley",
            "Moe Dunford"
        ],
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BM2FhM2E1MTktMDYwZi00ODA1LWI0YTYtN2NjZjM3ODFjYmU5XkEyXkFqcGdeQXVyMjY1ODQ3NTA@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
        "id": "5",
        "title": "Beast of Burden",
        "year": "2018",
        "genres": [
            "Action",
            "Crime",
            "Drama"
        ],
        "ratings": [
            9,
            5,
            5,
            5,
            5,
            6,
            10,
            6,
            6,
            9,
            6,
            2,
            2,
            9,
            4,
            6,
            6,
            9,
            7,
            8,
            7,
            10,
            8,
            5,
            3,
            1,
            1,
            5,
            6,
            2
        ],
        "contentRating": "R",
        "releaseDate": "2018-02",
        "storyline": "Sean Haggerty only has an hour to deliver his illegal cargo. An hour to reassure a drug cartel, a hitman, and the DEA that nothing is wrong. An hour to make sure his wife survives. And he must do it all from the cockpit of his Cessna.",
        "actors": [
            "Daniel Radcliffe",
            "Grace Gummer",
            "Pablo Schreiber"
        ],
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjEyNTM3MDQ2NV5BMl5BanBnXkFtZTgwMDI5Nzk1NDM@._V1_SY500_CR0,0,336,500_AL_.jpg"
    },
    {
        "id": "6",
        "title": "The Chamber",
        "year": "2016",
        "genres": [
            "Horror",
            "Thriller"
        ],
        "ratings": [
            2,
            10,
            7,
            10,
            9,
            9,
            7,
            4,
            6,
            2,
            1,
            10,
            9,
            4,
            6,
            8,
            3,
            5,
            1,
            1,
            1,
            5,
            6,
            9,
            5,
            4,
            8,
            8,
            8,
            8
        ],
        "contentRating": "",
        "releaseDate": "2017-03-10",
        "storyline": "A claustrophobic survival thriller set beneath the Yellow Sea off the coast of North Korea where the pilot of a small submersible craft and a three man Special Ops team on a secret recovery mission become trapped underwater in a fight for survival.",
        "actors": [
            "Johannes Kuhnke",
            "Charlotte Salt",
            "James McArdle"
        ],
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNTVlODgwMjgtZGUzMy00ZTY1LWIyMDEtYTI2Y2JlYzVjZTNkXkEyXkFqcGdeQXVyNTg0MDM1MzY@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
        "id": "7",
        "title": "Survivors Guide to Prison",
        "year": "2018",
        "genres": [
            "Documentary"
        ],
        "ratings": [
            7,
            5,
            9,
            6,
            6,
            8,
            7,
            6,
            10,
            6,
            6,
            3,
            9,
            6,
            2,
            5,
            8,
            9,
            1,
            3,
            7,
            4,
            1,
            2,
            4,
            3,
            6,
            10,
            10,
            8
        ],
        "contentRating": "",
        "releaseDate": "2018-02-23",
        "storyline": "Following the stories of Bruce Lisker and Reggie Cole who spent year after year in prison for murders they didn't commit - audiences get a harrowing look at how barbaric the US justice system is. The film ultimately asks how we can survive the prison model at all, and looks at better solutions for conflict resolution, harm reduction, crime and more. Hosted by filmmaker Matthew Cooke and guest hosting representatives from the massive range of Americans joining forces to change this broken system.                Written by\nanonymous",
        "actors": [
            "Susan Sarandon",
            "Patricia Arquette",
            "Danny Trejo"
        ],
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNzhmNmI5MDMtZDEyOC00ODkyLTkwODItODQzODAzY2QyZjVlXkEyXkFqcGdeQXVyMzQwMTY2Nzk@._V1_SY500_CR0,0,357,500_AL_.jpg"
    },
    {
        "id": "8",
        "title": "Red Sparrow",
        "year": "2018",
        "genres": [
            "Mystery",
            "Thriller"
        ],
        "ratings": [
            9,
            3,
            3,
            7,
            2,
            3,
            2,
            5,
            6,
            3,
            5,
            6,
            2,
            3,
            3,
            9,
            1,
            2,
            7,
            10,
            3,
            6,
            2,
            4,
            6,
            1,
            10,
            6,
            4,
            7
        ],
        "contentRating": "R",
        "releaseDate": "2018-03-02",
        "storyline": "A young Russian intelligence officer is assigned to seduce a first-tour CIA agent who handles the CIA's most sensitive penetration of Russian intelligence. The two young officers collide in a charged atmosphere of trade-craft, deception, and inevitably forbidden passion that threatens not just their lives but the lives of others as well.",
        "actors": [
            "Jennifer Lawrence",
            "Joel Edgerton",
            "Charlotte Rampling"
        ],
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTA3MDkxOTc4NDdeQTJeQWpwZ15BbWU4MDAxNzgyNTQz._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
        "id": "9",
        "title": "Death Wish",
        "year": "2018",
        "genres": [
            "Action",
            "Crime",
            "Drama"
        ],
        "ratings": [
            2,
            9,
            5,
            9,
            7,
            7,
            4,
            5,
            5,
            6,
            5,
            3,
            7,
            10,
            4,
            8,
            2,
            9,
            7,
            10,
            2,
            10,
            3,
            1,
            4,
            6,
            4,
            6,
            7,
            3
        ],
        "contentRating": "R",
        "releaseDate": "2018-04-13",
        "storyline": "Dr. Paul Kersey (Bruce Willis) is a surgeon who only sees the aftermath of his city's violence as it's rushed into his ER -until his wife (Elisabeth Shue) and college-age daughter (Camila Morrone) are viciously attacked in their suburban home. With the police overloaded with crimes, Paul, burning for revenge, hunts for his family's assailants to deliver justice. As the anonymous slayings of criminals grabs the media's attention, the city wonders if this deadly avenger is a guardian angel...or a grim reaper. Fury and fate collide in the intense action-thriller Death Wish.                Written by\nMGM",
        "actors": [
            "Bruce Willis",
            "Vincent D'Onofrio",
            "Elisabeth Shue"
        ],
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTkzNjU3MjE0MF5BMl5BanBnXkFtZTgwNTIyNDk0NDM@._V1_SY400_SX270_AL_.jpg"
    },
    {
        "id": "10",
        "title": "They Remain",
        "year": "2018",
        "genres": [
            "Thriller"
        ],
        "ratings": [
            3,
            6,
            9,
            3,
            9,
            6,
            4,
            1,
            10,
            1,
            1,
            9,
            7,
            7,
            6,
            8,
            6,
            6,
            6,
            8,
            8,
            10,
            7,
            2,
            9,
            10,
            8,
            6,
            9,
            4
        ],
        "contentRating": "",
        "releaseDate": "2018-01-28",
        "storyline": "Two scientists who share a romantic history are tasked with investigating unnatural animal behaviour on the site of a Manson Family-style cult's compound.",
        "actors": [
            "William Jackson Harper",
            "Rebecca Henderson"
        ],
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjI0NTEzMTk1OV5BMl5BanBnXkFtZTgwNTMwNDY3NDM@._V1_SY500_CR0,0,349,500_AL_.jpg"
    },
    {
        "id": "11",
        "title": "Submission",
        "year": "2017",
        "genres": [
            "Drama"
        ],
        "ratings": [
            5,
            3,
            9,
            8,
            9,
            1,
            7,
            8,
            6,
            5,
            3,
            1,
            8,
            4,
            7,
            2,
            9,
            9,
            2,
            2,
            4,
            5,
            9,
            10,
            8,
            5,
            7,
            6,
            4,
            5
        ],
        "contentRating": "",
        "releaseDate": "2017-10-13",
        "storyline": "A cynical college professor takes a keen interest in a talented young writing student.",
        "actors": [
            "Stanley Tucci",
            "Addison Timlin",
            "Kyra Sedgwick"
        ],
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjQ4NDkwMzM4OF5BMl5BanBnXkFtZTgwNzE3MzI3NDM@._V1_SY500_CR0,0,337,500_AL_.jpg"
    }
]